remo/base/urls.py
from django.conf.urls import url

from remo.base import views as base_views

urlpatterns = [
    url(r'^$', base_views.main, name='main'),
    url(r'^capture-csp-violation$', base_views.capture_csp_violation,
        name='capture-csp-violation'),
]

remo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve as serve_view

from remo.base import views as base_views
from remo.profiles import views as profiles_views


# Monkeypatch log_settings
import log_settings  # noqa

handler404 = base_views.custom_404
handler500 = base_views.custom_500
robots_txt = base_views.robots_txt

urlpatterns = [
    # 'me' urls
    url(r'^me/$', profiles_views.view_my_profile, name='profiles_view_my_profile'),
    # Profiles
    url(r'^u/', include('remo.profiles.user_urls')),
    url(r'^people/', include('remo.profiles.people_urls')),
    # Events
    url(r'^e/', include('remo.events.e_urls')),
    url(r'^events/', include('remo.events.event_urls')),
    # Reports
    url(r'^reports/', include('remo.reports.report_urls')),
    # Featuredrep
    url(r'^featured/', include('remo.featuredrep.urls')),
    # Login
    url(r'oidc/', include('mozilla_django_oidc.urls')),
    # API
    url(r'^api/', include('remo.api.urls')),
    url(r'^', include('remo.base.urls')),
    # Dashboard
    url(r'^dashboard/', include('remo.dashboard.urls')),
    # Action Items
    url(r'^actions/', include('remo.dashboard.action_urls')),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Voting
    url(r'^voting/', include('remo.voting.voting_urls')),
    url(r'^v/', include('remo.voting.v_urls')),
    # Portal base content
    url(r'^content/', include('remo.base.content_urls')),
    # Portal settings
    url(r'^settings/', include('remo.base.settings_urls')),
    # Generate a robots.txt
    url(r'^robots\.txt$', robots_txt),
    # contribute.json url
    url(r'^(?P<path>contribute\.json)$', serve_view, {'document_root': settings.ROOT}),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^404/$', handler404, name='404'),
        url(r'^500/$', handler500, name='500')
    ]
    urlpatterns += staticfiles_urlpatterns()

remo/base/models.py
from django.db import models


class GenericActiveManager(models.Manager):
    """
    Generic custom manager to fetch only the objects marked with
    an active flag.
    """
    def get_queryset(self):
        return super(GenericActiveManager, self).get_queryset().filter(active=True)

remo/events/models.py
from pytz import timezone

from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import now

from uuslug import uuslug as slugify

from remo.base.models import GenericActiveManager
from remo.base.tasks import send_remo_mail
from remo.dashboard.models import ActionItem, Item
from remo.profiles.models import FunctionalArea
from remo.remozilla.models import Bug


SIMILAR_EVENTS = 3
POST_EVENT_METRICS_ACTION = 'Submit post event metrics for'


@python_2_unicode_compatible
class Attendance(models.Model):
    """Attendance Model."""
    user = models.ForeignKey(User)
    event = models.ForeignKey('Event')
    email = models.BooleanField(default=True)
    date_subscribed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return u'%s %s' % (self.user, self.event)


@python_2_unicode_compatible
class EventGoal(models.Model):
    """Event Goals Model."""
    name = models.CharField(db_index=True, max_length=127, unique=True)
    slug = models.SlugField(blank=True, max_length=127)
    active = models.BooleanField(default=True)

    objects = models.Manager()
    active_objects = GenericActiveManager()

    def save(self, *args, **kwargs):
        # Create unique slug
        if not self.slug:
            self.slug = slugify(self.name, instance=self)
        super(EventGoal, self).save(*args, **kwargs)

    def get_absolute_delete_url(self):
        return reverse('delete_event_goal', kwargs={'pk': self.id})

    def get_absolute_edit_url(self):
        return reverse('edit_event_goal', kwargs={'pk': self.id})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'event goal'
        verbose_name_plural = 'event goals'


@python_2_unicode_compatible
class EventMetric(models.Model):
    """New generation event metrics."""
    name = models.CharField(max_length=100)
    active = models.BooleanField(default=True)

    objects = models.Manager()
    active_objects = GenericActiveManager()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_edit_url(self):
        return reverse('edit_metric', kwargs={'pk': self.id})


@python_2_unicode_compatible
class Event(models.Model):
    """Event Model."""
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, max_length=100)
    start = models.DateTimeField()
    end = models.DateTimeField()
    timezone = models.CharField(max_length=100)
    venue = models.CharField(max_length=150)
    city = models.CharField(max_length=50, blank=False, default='')
    region = models.CharField(max_length=50, null=False, blank=True, default='')
    country = models.CharField(max_length=50)
    lat = models.FloatField()
    lon = models.FloatField()
    external_link = models.URLField(max_length=300, null=True, blank=True)
    owner = models.ForeignKey(User, related_name='events_created')
    planning_pad_url = models.URLField(blank=True, max_length=300)
    estimated_attendance = models.PositiveIntegerField()
    actual_attendance = models.PositiveIntegerField(null=True, blank=True)
    description = models.TextField(validators=[MaxLengthValidator(500), MinLengthValidator(20)])
    extra_content = models.TextField(blank=True, default='')
    mozilla_event = models.BooleanField(default=False)
    hashtag = models.CharField(max_length=50, blank=True, default='')
    attendees = models.ManyToManyField(User, related_name='events_attended', through='Attendance')
    converted_visitors = models.PositiveIntegerField(editable=False, default=0)
    swag_bug = models.ForeignKey(Bug, null=True, blank=True,
                                 on_delete=models.SET_NULL,
                                 related_name='event_swag_requests')
    budget_bug = models.ForeignKey(Bug, null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name='event_budget_requests')
    times_edited = models.PositiveIntegerField(default=0, editable=False)
    categories = models.ManyToManyField(FunctionalArea,
                                        related_name='events_categories',
                                        blank=True)
    goals = models.ManyToManyField(EventGoal, related_name='events_goals', blank=True)
    metrics = models.ManyToManyField(EventMetric, through='EventMetricOutcome')
    has_new_metrics = models.BooleanField(default=True)
    action_items = generic.GenericRelation(ActionItem)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)
    campaign = models.ForeignKey('reports.Campaign', related_name='events', null=True, blank=False)

    def get_absolute_url(self):
        return reverse('events_view_event', kwargs={'slug': self.slug})

    def get_absolute_edit_url(self):
        return reverse('events_edit_event', kwargs={'slug': self.slug})

    def __str__(self):
        """Event unicode representation."""
        return self.name

    def _make_local(self, obj):
        """Return a datetime obj localized in self.timezone."""
        if not obj:
            return None
        t = timezone(self.timezone)
        return obj.astimezone(t)

    def save(self, *args, **kwargs):
        """Override save method for custom functionality."""
        # Create unique slug
        if not self.pk:
            self.slug = slugify(self.name, instance=self)

        # Update action items
        if self.pk:
            current_event = Event.objects.get(id=self.pk)
            if current_event.owner != self.owner:
                model = ContentType.objects.get_for_model(self)
                action_items = ActionItem.objects.filter(content_type=model, object_id=self.pk)
                action_items.update(user=self.owner)

        super(Event, self).save(*args, **kwargs)

        # Subscribe owner to event
        Attendance.objects.get_or_create(event=self, user=self.owner)

    @property
    def local_start(self):
        """Property to start datetime localized."""
        return self._make_local(self.start)

    @property
    def local_end(self):
        """Property to end datetime localized."""
        return self._make_local(self.end)

    @property
    def is_past_event(self):
        """Property to check is event is in the past."""
        if self.id and self.end:
            return now() > self.end
        return None

    def get_similar_events(self):
        """Implement 3-events-like-this functionality.

        Specs:

        * Return future events that match the same country and one or
          more categories.
        * If less than 3 matches, show upcoming events with the same country.
        * If less than 3 matches, show upcoming events with the same category.
        * Order by date, earliest date first.

        """

        events = Event.objects.filter(start__gte=now()).exclude(pk=self.pk)
        country = Q(country=self.country)
        category = Q(categories__in=self.categories.all())

        if (events.filter(country, category).distinct().count() < SIMILAR_EVENTS):
            if events.filter(country).count() < SIMILAR_EVENTS:
                return events.filter(category).distinct()
            return events.filter(country)
        return events.filter(country, category).distinct()

    def get_action_items(self):
        action_items = []

        # Get action items for post event metrics
        outcome = self.eventmetricoutcome_set.filter(outcome__isnull=False)
        if self.is_past_event and not outcome and self.has_new_metrics:
            name = u'{0} {1}'.format(POST_EVENT_METRICS_ACTION, self.name)
            action_item = Item(name, self.owner, ActionItem.NORMAL, None)
            action_items.append(action_item)
        return action_items

    class Meta:
        ordering = ['start']
        permissions = (('can_subscribe_to_events', 'Can subscribe to events'),
                       ('can_edit_events', 'Can edit events'),
                       ('can_delete_events', 'Can delete events'),
                       ('can_delete_event_comments',
                        'Can delete event comments'))


class EventMetricOutcome(models.Model):
    """New generation event metric stats."""
    event = models.ForeignKey(Event)
    metric = models.ForeignKey(EventMetric)
    expected_outcome = models.PositiveIntegerField()
    outcome = models.PositiveIntegerField(null=True, blank=True)
    details = models.TextField(validators=[MaxLengthValidator(1500)], blank=True, default='')

    class Meta:
        verbose_name = 'event outcome'
        verbose_name_plural = 'events outcome'

    def save(self, *args, **kwargs):
        super(EventMetricOutcome, self).save(*args, **kwargs)

        # Resolve action items for post event metrics
        # if only is past event
        if self.event.is_past_event:
            ActionItem.resolve(instance=self.event, user=self.event.owner, name=self.event.name)


class EventComment(models.Model):
    """Comments in Event."""
    user = models.ForeignKey(User)
    event = models.ForeignKey(Event)
    created_on = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()

    class Meta:
        ordering = ['id']


class Metric(models.Model):
    """Metrics Model."""
    event = models.ForeignKey('Event')
    title = models.CharField(max_length=300)
    outcome = models.CharField(max_length=300)

remo/base/forms.py
import happyforms

from django import forms
from django.contrib import messages

from remo.base.tasks import send_remo_mail
from remo.profiles.models import UserProfile


class BaseEmailUsersForm(happyforms.Form):
    """Base form to send email to multiple users."""
    subject = forms.CharField(label='', widget=(
        forms.TextInput(attrs={'placeholder': 'Subject',
                               'required': 'required',
                               'class': 'input-text big'})))
    body = forms.CharField(label='', widget=(
        forms.Textarea(attrs={'placeholder': 'Body of email',
                              'required': 'required',
                              'class': 'flat long'})))


class EmailUsersForm(BaseEmailUsersForm):
    """Generic form to send email to multiple users."""

    def __init__(self, users, *args, **kwargs):
        """Initialize form.

        Dynamically set fields for the recipients of the mail.
        """
        super(EmailUsersForm, self).__init__(*args, **kwargs)
        for user in users:
            # Insert method is used to override the order of form fields
            form_widget = forms.CheckboxInput(
                attrs={'class': 'input-text-big'})
            self.fields.update([(str(user.id), forms.BooleanField(label=user,
                                                                  initial=False,
                                                                  required=False,
                                                                  widget=form_widget))])

    def send_mail(self, request):
        """Send mail to recipients list."""
        recipients_list = []
        for field in self.fields:
            if (isinstance(self.fields[field], forms.BooleanField)
                    and self.cleaned_data[field]):
                recipients_list.append(long(field))

        if recipients_list:
            from_email = '%s <%s>' % (request.user.get_full_name(),
                                      request.user.email)
            send_remo_mail.delay(sender=from_email,
                                 recipients_list=recipients_list,
                                 subject=self.cleaned_data['subject'],
                                 message=self.cleaned_data['body'])
            messages.success(request, 'Email sent successfully.')
        else:
            messages.error(request, ('Email not sent. Please select at '
                                     'least one recipient.'))


class EmailMentorForm(BaseEmailUsersForm):
    """Generic form to send email to a user's mentor."""
    subject = forms.CharField(required=False)

    def send_email(self, request, subject='', message=None,
                   template=None, data=None):
        """Send an email to user's mentor"""
        mentor = request.user.userprofile.mentor
        if mentor:
            from_email = '%s <%s>' % (request.user.get_full_name(),
                                      request.user.email)
            send_remo_mail.delay(sender=from_email,
                                 recipients_list=[mentor.id],
                                 subject=subject,
                                 message=message,
                                 email_template=template,
                                 data=data)


class EditSettingsForm(happyforms.ModelForm):
    """Form to edit user settings regarding mail preferences."""
    receive_email_on_add_comment = forms.BooleanField(
        required=False, initial=True,
        label=('Receive email when a user comments on a report.'))
    receive_email_on_add_event_comment = forms.BooleanField(
        required=False, initial=True,
        label=('Receive email when a user comments on an event.'))
    receive_email_on_add_voting_comment = forms.BooleanField(
        required=False, initial=True,
        label=('Receive email when a user comments on an poll.'))

    class Meta:
        model = UserProfile
        fields = ['receive_email_on_add_comment',
                  'receive_email_on_add_event_comment',
                  'receive_email_on_add_voting_comment']

remo/base/templates/404.jinja
{% extends "main.jinja" %}
{% block pagetitle %}Page not found!{% endblock %}

{% block content %}
{{ super() }}
<!-- 404 Modal -->
<div id="404-error" class="reveal-modal small">
  <p class="lead">oops, we couldn't find that!</p>
  <h2>404 - Not found</h2>
  <p>We are sorry but we couldn't find the page you requested.</p>
  <p>Check the address for typing errors such as ww.example.com instead of www.example.com</p>
  <a class="close-reveal-modal">&#215;</a>
</div>
<!-- 404 Modal End -->
{% endblock %}

{% block bottomextra %}
  {{ super() }}
  {% compress js %}
    <script src="{{ static('base/js/404.js') }}"></script>
  {% endcompress %}
{% endblock %}

remo/base/templates/500.jinja
{% extends "base_fd4.jinja" %}
{% block pagetitle %}Server Error{% endblock %}

{% block content %}

<!-- Adding new rep -->
<div class="row">
  <div class="large-12 columns">
    <h2>500 - Server Error</h2>
  </div>
</div>

<!-- Two column block -->
<div class="row">
  <div class="large-12 columns">
    <p>The Force is weak with our servers.</p>
    <p>Our Jedis have been notified accordingly.</p>
  </div>
</div>
{% endblock %}

remo/base/templates/base_content_edit.jinja
{% extends "base_fd4.jinja" %}
{% block pagetitle %}
  {% if creating %}
    Mozilla Reps - Add {{ verbose_name }}
  {% else %}
    Mozilla Reps - Edit {{ verbose_name }}
  {% endif %}
{% endblock %}
{% block content %}

<main role="main">
  <form method="post">
    {% csrf_token %}
    <div class="row">
      <div class="large-6 columns">
        {% if creating %}
          <h1>Add {{ verbose_name }}</h1>
        {% else %}
          <h1>Edit {{ verbose_name }}</h1>
        {% endif %}
      </div>
    </div>
    <div class="row base-content-edit">
      <div class="large-6 columns">
        {{ field_with_attrs(form.name, placeholder='Name', title='Name') }}
        {{ field_errors(form.name) }}
        <label for="id_active">Set this {{ verbose_name }} as active</label>
        {{ form.active }}
      </div>
    </div>
    <div class="row">
      <div class="large-6 columns align-right">
        <button id="save-object" type="submit"
                class="small button confirm">
          Save {{ verbose_name }}
        </button>
      </div>
    </div>
  </form>
</main>
{% endblock %}

remo/base/templates/base_content_list.jinja
{% extends "base_fd4.jinja" %}
{% block pagetitle %}Mozilla Reps - {{ verbose_name_plural|capitalize }}{% endblock %}

{% block content %}
<main role="main">
  <div class="row">
    <div class="large-12 columns">
      <h1>{{ verbose_name_plural|capitalize }}</h1>
    </div>
    <div class="large-3 columns align-right">
      <a href="{{ create_object_url }}" class="button small update" role="button"
         id="create-button">Create {{ verbose_name }}</a>
    </div>
  </div>

  <div class="row base-content-list">
    <div class="large-12 columns">
      <table class="dashboard-table">
        <thead>
          <tr>
            <th class="dashboard-clickable type-string">Name</th>
            <th class="dashboard-clickable type-string">Active</th>
            <th class="dashboard-clickable type-string">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>
                {{ object.name }}
              </td>
              <td>
                {% if object.active %}
                  <span class="pict-table-icon tick"></span>
                {% endif %}
              </td>
              <td>
              {% if get_attr(object, 'is_editable', True)  %}
                <a href="{{ object.get_absolute_edit_url() }}"
                   class="pictogram-button">
                  <span class="pict-icon large pencil"></span>
                </a>
              {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>

{% endblock %}

{% block bottomextra %}
  {% compress js %}
    <script src="{{ static('base/js/base_content_edit.js') }}"></script>
    <script src="{{ static('base/js/stupidtable.js') }}"></script>
  {% endcompress %}
{% endblock %}

remo/base/templates/edit_availability.jinja
{% extends "base_fd4.jinja" %}

{% block pagetitle %}
  {{ super() }} - Taking a break notification
{% endblock %}

{% block content %}
<main role="main" class="availability-main">
  <form id="edit-availability-form" method="post">
    {% csrf_token %}

    {% if created %}
      {% if status_form.errors %}
        <div class="row">
          <div class="large-12 columns">
            <small role="alert" class="error">Please correct the errors below.</small>
          </div>
        </div>
      {% endif %}
      <div class="row">
        <div class="large-6 columns">
          <h1>
            Taking a break notification
          </h1>
          <p>
            We all need breaks. Let us know when you will be back and if a Rep
            will replace you while you are taking a break.
          </p>
        </div>
      </div>

      <!-- Start Date section -->
      <div class="row">
        <div class="large-6 columns">
          <div class="row">
            <div class="large-1 columns">
              <div class="pict-icon large time"></div>
            </div>
            <div class="large-11 columns">
              <label for="id_start_date">
                I plan to take a break starting on
              </label>
              <div id="availability-date">
                {{ field_with_attrs(status_form.start_date,
                                    class="datepicker",
                                    autocomplete="off",
                                    placeholder="DD-MM-YYYY",
                                    readonly="readonly") }}
              </div>
              {{ field_errors(status_form.start_date) }}
            </div>
          </div>
        </div>
      </div>

      <!-- Return Date section -->
      <div class="row">
        <div class="large-6 columns">
          <div class="row">
            <div class="large-1 columns">
              <!-- Empty column -->
            </div>
            <div class="large-11 columns">
              <label class="required" for="id_expected_date">
                I plan to be active again in the Reps Program starting on
              </label>
              <div id="availability-date">
                {{ field_with_attrs(status_form.expected_date,
                                    class="datepicker",
                                    autocomplete="off",
                                    placeholder="DD-MM-YYYY",
                                    readonly="readonly") }}
              </div>
              {{ field_errors(status_form.expected_date) }}
            </div>
          </div>
        </div>
      </div>

      <!-- Replacement Rep -->
      <div class="row">
        <div class="large-6 columns">
          <div class="row">
            <div class="large-1 columns">
              <div class="pict-icon large people"></div>
            </div>
            <div class="large-11 columns">
              <p class="required">
                Will a Rep replace you while you are unavailable?
              </p>
              <div id="replacement-rep-radio">
                <p>
                  {% for choice in status_form.is_replaced %}
                    {{ choice }}
                  {% endfor %}
                </p>
              </div>

              <div id="replacement-rep-panel">
                <label class="required" for="id_replacement_rep">
                  Which Rep will replace you?
                </label>
                <div id="replacement-rep">
                  {{ status_form.replacement_rep }}
                </div>
                {{ field_errors(status_form.replacement_rep) }}
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Mail/unavailability reason section -->
      <div class="row">
        <div class="large-6 columns">
          <div class="row">
            <div class="large-1 columns">
              <div class="pict-icon large edit"></div>
            </div>
            <div class="large-11 columns">
              <label class="required" for="id_body">
                Why are you taking a break?
              </label>
              <div id="availability-date">
                {{ field_with_attrs(email_form.body,
                  placeholder="Any information entered here is sent to your mentor but not stored anywhere",
                  rows=4) }}
              </div>
              {{ field_errors(email_form.body) }}
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">
          <p>
            Your mentor will be notified of your break.
          </p>
        </div>
      </div>
    {% else %}
      <!-- Rep available section -->
      <div class="row">
        <div class="large-12 columns">
          <h2>
            Update your availability status.
          </h2>
          <div class="large-12 columns">
            <p>
              Click the submit button below if you are ready
              to resume your activities.
            </p>
            {{ status_form.expected_date }}
          </div>
        </div>
      </div>
    {% endif %}

    <div class="row">
      <div class="large-12 columns">
        <button type="submit" class="small button confirm">Submit</button>
      </div>
    </div>
  </form>
</main>

{% endblock %}

{% block bottomextra %}
  {% compress css %}
    <link rel="stylesheet" href="{{ static('events/css/jquery-ui-1.10.0.custom.css') }}"
          media="screen,projection,tv" />
  {% endcompress %}
  {% compress js %}
    <script src="{{ static('events/js/jquery-ui-1.10.0.custom.js') }}"></script>
    <script src="{{ static('base/js/edit_availability.js') }}"></script>
  {% endcompress %}
{% endblock %}

remo/base/templates/form-error.html
{% if field.errors %}
  {% if field.errors is string %}
    <small class="error">
      {{ field.errors }}
    </small>
  {% else %}
    {% for error in field.errors %}
      <small class="error">
        {{ error }}
      </small>
    {% endfor %}
  {% endif %}
{% endif %}

remo/base/templates/form-error.jinja
{% if field.errors %}
  {% if field.errors is string %}
    <small class="error">
      {{ field.errors }}
    </small>
  {% else %}
    {% for error in field.errors %}
      <small class="error">
        {{ error }}
      </small>
    {% endfor %}
  {% endif %}
{% endif %}

remo/base/templates/main.jinja
{% extends "base_fd4.jinja" %}

{% block content %}

<main role="main">
  <!-- Sidereel Orbit featured images -->
  <div class="row orbit">
    <div class="large-12 columns slidereel">
      <ul id="featured" data-orbit>
        <li>
          <img src="{{ static('base/img/remo/show1.png') }}" alt="Mozilla Reps and others" />
        </li>
        <li>
          <img src="{{ static('base/img/remo/show2.png') }}" alt="Mozilla Reps in action" />
        </li>
        <li>
          <img src="{{ static('base/img/remo/show3.png') }}" alt="Mozilla Reps in action" />
        </li>
      </ul>
    </div>
  </div>

  <!-- 3 Sections are here -->
  <div class="row">

    <!-- About section -->
    <div class="large-4 columns main-section">
      <div id="about">
        <h3>
          about:reps
        </h3>
        <p>
          Reps are passionate Mozillians who mobilize and develop functional and
          local/regional Mozilla communities. They are committed to educate and
          empower people to support Mozilla’s mission and contribute to the project
          based on Mozilla’s leadership agreements.
        </p>
        <p>
          They are also creating collaborations with other local communities
          to expand Mozilla’s outreach in the open source ecosystem.
        </p>
        <p>
          You can learn more about the program
          <a href="https://wiki.mozilla.org/Reps">here</a>.
        </p>
      </div>
    </div>

    <!-- Featured Rep section -->
    <div class="large-4 columns main-section" id="featured-reps">
      <h3>
        Rep of the Month
      </h3>
      {% if featuredrep %}
        {% for user in featuredrep.users.all() %}
          <div class="row">
            <div class="large-4 columns">
              <img src="{{ user|get_avatar_url(80) }}" id="main-featured-avatar"
                  alt="Profile picture of {{ user.first_name }} {{ user.last_name }}">
            </div>
            <div class="large-8 columns">
              <h5>
                <a href="{{ url('profiles_view_profile', user.userprofile.display_name) }}">
                  {{ user.first_name }}<br>{{ user.last_name }}
                </a>
              </h5>
              {{ user.userprofile.city }}, {{ user.userprofile.country }}
            </div>
          </div>
        {% endfor %}
        <div class="row">
          <div class="large-12 columns">
            <div class="markdown">
              {{ featuredrep.text|markdown }}
            </div>
          </div>
        </div>
      {% else %}
        <div class="large-12 columns">
          None for this month!
        </div>
      {% endif %}

      <div class="row">
        <a class="large-12 columns more-posts" href="/featured/">See past featured Reps...</a>
      </div>
    </div>

    <!-- Planet Section -->
    <div class="large-4 columns main-section">
      <h3>
        Reps Planet
      </h3>
      <div id="planet">
        {% for entry in planet_entries %}
          <div class="ItemTitle">
            <a href="{{ entry.link }}" target="_blank">{{ entry.title }}</a>
          </div>
          <div class="ItemContent">{{ entry.description }}</div>
        {% endfor %}
      </div>
      <div class="row">
        <a class="large-12 columns more-posts" href="https://planet.mozillareps.org">See all posts in planet...</a>
      </div>
    </div>

  </div>
</main>
{% endblock %}

{% block bottomextra %}
  {% compress js %}
    <script src="{{ static('base/js/orbit.js') }}"></script>
  {% endcompress %}
{% endblock %}

remo/base/templates/multi_event_ical_template.jinja
BEGIN:VCALENDAR
PRODID:-//reps.mozilla.com Events//
VERSION:2.0
METHOD:PUBLISH
{% for event in events %}
BEGIN:VEVENT
UID:{{ host }}@{{ event.id }}
CLASS:PUBLIC
DTSTAMP:{{ date_now|format_datetime_utc }}Z
DTSTART:{{ event.start|format_datetime_utc }}Z
DTEND:{{ event.end|format_datetime_utc }}Z
{{ "LOCATION:%s, %s, %s"|format(event.venue, event.city, event.country)|ical_escape_char|ical_format_lines }}
{{ "SUMMARY:%s"|format(event.name)|ical_escape_char|ical_format_lines }}
{{ "DESCRIPTION:%s"|format(event.description)|ical_escape_char|ical_format_lines }}
{{ "URL:%s%s"|format(host, url('events_view_event', slug=event.slug))|ical_escape_char|ical_format_lines }}
SEQUENCE:{{ event.times_edited }}
X-COORDINATES-LAT:{{ event.lat }}
X-COORDINATES-LON:{{ event.lon }}
X-COUNTRY-CODE:{{ event.country|get_country_code }}
END:VEVENT
{% endfor %}
END:VCALENDAR