remo/featuredrep/urls.py
from django.conf.urls import url

from remo.featuredrep import views

urlpatterns = [
    url(r'^$', views.list_featured, name='featuredrep_list_featured'),
    url(r'^add/$', views.edit_featured, name='featuredrep_add_featured'),
    url(r'^edit/(?P<feature_id>\d+)/$', views.edit_featured, name='featuredrep_edit_featured'),
    url(r'^delete/(?P<feature_id>\d+)/$', views.delete_featured,
        name='featuredrep_delete_featured'),
]

remo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve as serve_view

from remo.base import views as base_views
from remo.profiles import views as profiles_views


# Monkeypatch log_settings
import log_settings  # noqa

handler404 = base_views.custom_404
handler500 = base_views.custom_500
robots_txt = base_views.robots_txt

urlpatterns = [
    # 'me' urls
    url(r'^me/$', profiles_views.view_my_profile, name='profiles_view_my_profile'),
    # Profiles
    url(r'^u/', include('remo.profiles.user_urls')),
    url(r'^people/', include('remo.profiles.people_urls')),
    # Events
    url(r'^e/', include('remo.events.e_urls')),
    url(r'^events/', include('remo.events.event_urls')),
    # Reports
    url(r'^reports/', include('remo.reports.report_urls')),
    # Featuredrep
    url(r'^featured/', include('remo.featuredrep.urls')),
    # Login
    url(r'oidc/', include('mozilla_django_oidc.urls')),
    # API
    url(r'^api/', include('remo.api.urls')),
    url(r'^', include('remo.base.urls')),
    # Dashboard
    url(r'^dashboard/', include('remo.dashboard.urls')),
    # Action Items
    url(r'^actions/', include('remo.dashboard.action_urls')),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Voting
    url(r'^voting/', include('remo.voting.voting_urls')),
    url(r'^v/', include('remo.voting.v_urls')),
    # Portal base content
    url(r'^content/', include('remo.base.content_urls')),
    # Portal settings
    url(r'^settings/', include('remo.base.settings_urls')),
    # Generate a robots.txt
    url(r'^robots\.txt$', robots_txt),
    # contribute.json url
    url(r'^(?P<path>contribute\.json)$', serve_view, {'document_root': settings.ROOT}),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^404/$', handler404, name='404'),
        url(r'^500/$', handler500, name='500')
    ]
    urlpatterns += staticfiles_urlpatterns()

remo/featuredrep/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now


class FeaturedRep(models.Model):
    """Featured Rep model.

    Featured Rep -or Rep of the Month- relates existing users with
    some text explaining why they are so cool.

    """
    created_on = models.DateTimeField(null=True, blank=True)
    updated_on = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(User, related_name='reps_featured')
    text = models.TextField(blank=False, null=False)
    users = models.ManyToManyField(User, related_name='featuredrep_users')

    class Meta:
        ordering = ['-created_on']
        get_latest_by = 'updated_on'
        permissions = (('can_edit_featured', 'Can edit featured reps'),
                       ('can_delete_featured', 'Can delete featured reps'))

    def save(self, *args, **kwargs):
        """Override save method for custom functionality"""

        # This allows to override the updated_on through the admin interface
        self.updated_on = kwargs.pop('updated_on', None)

        if not self.updated_on:
            self.updated_on = now()
        if not self.pk:
            self.created_on = now()
        super(FeaturedRep, self).save(*args, **kwargs)

remo/featuredrep/forms.py
from django import forms
from django.contrib.auth.models import User

import happyforms

from models import FeaturedRep


class FeaturedRepForm(happyforms.ModelForm):
    """Form to create a new FeaturedRep object."""
    users = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(
            userprofile__registration_complete=True,
            groups__name='Rep').order_by('first_name'))

    class Meta:
        model = FeaturedRep
        fields = ['users', 'text']
        widgets = {'users': forms.SelectMultiple()}

remo/featuredrep/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_control, never_cache
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings

from remo.base.decorators import permission_check

import forms
from models import FeaturedRep


@cache_control(private=True, max_age=60 * 10)
def list_featured(request):
    """List all Featured Reps."""
    featured_list = FeaturedRep.objects.all()

    paginator = Paginator(featured_list,
                          settings.ITEMS_PER_PAGE)
    page = request.GET.get('page')

    try:
        featured = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        featured = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver last page of results.
        featured = paginator.page(paginator.num_pages)

    return render(request, 'featuredrep_list.jinja', {'objects': featured})


@never_cache
@permission_check(permissions=['featuredrep.can_edit_featured'])
def edit_featured(request, feature_id=None):
    """Create or edit a Featured Rep.

    If feature_id == None then a new Featured Rep entry is created,
    otherwise the Featured Rep entry with id == feature_id is edited.

    """
    if feature_id:
        feature = get_object_or_404(FeaturedRep, pk=feature_id)
        post_to = reverse('featuredrep_edit_featured', args=[feature_id])
    else:
        feature = FeaturedRep(created_by=request.user)
        post_to = reverse('featuredrep_add_featured')

    form = forms.FeaturedRepForm(request.POST or None, instance=feature)

    if form.is_valid():
        form.save()

        if feature_id:
            messages.success(
                request, 'Featured rep article successfuly edited.')
        else:
            messages.success(request, 'New featured rep article created.')

        return redirect('featuredrep_list_featured')

    # List only user that belong in Rep group and have completed
    # registration.
    reps = User.objects.filter(userprofile__registration_complete=True,
                               groups__name='Rep')

    return render(request, 'featuredrep_alter.jinja',
                  {'form': form, 'post_to': post_to, 'reps': reps})


@permission_check(permissions=['featuredrep.can_delete_featured'])
def delete_featured(request, feature_id):
    """Delete a Featured Rep entry."""
    if request.method == 'POST':
        feature = get_object_or_404(FeaturedRep, pk=feature_id)
        feature.delete()
        messages.success(request, 'Featured rep article successfuly deleted')

    return redirect('featuredrep_list_featured')

remo/featuredrep/templates/featuredrep_alter.jinja
{% extends "base_fd4.jinja" %}
{% block pagetitle %}Mozilla Reps - Add new featured rep{% endblock %}

{% block content %}
<main role="main" class="featured-reps">
  <form method="post" action="{{ post_to }}">
    {% csrf_token %}

    {% if form.errors %}
      <div class="row">
        <div class="large-12 columns">
          <small class="error">Please correct the errors below.</small>
        </div>
      </div>
    {% endif %}
    <div class="row">
      <div class="large-6 columns">
        <h5>
          Add or Edit Featured Reps article
        </h5>
      </div>
    </div>

    <div class="row">
      <div class="large-6 columns">
        <label class="required" for="id_users">
          Please specify the Featured Rep(s) for this month.
        </label>
        {{ field_with_attrs(form.users, size=18) }}
        {{ field_errors(form.users) }}
      </div>
      <div class="large-12 columns">
        <textarea class="flat" placeholder="Enter text for featured Rep"
                  name="text">{{ form.text.value() }}</textarea>
        <div class="required-field"></div>
        {{ field_errors(form.text) }}
        <p class="more-info">In this field you can use
          <a href="http://en.wikipedia.org/wiki/Markdown"
            target="_blank"> Markdown
          </a>
          syntax.
        </p>
        <button type="submit" class="featured-button small button">
          Add or Edit Featured Rep
        </button>
      </div>
    </div>
  </form>
</main>
{% endblock %}

remo/featuredrep/templates/featuredrep_list.jinja
{% extends "base_fd4.jinja" %}

{% block pagetitle %}Mozilla Reps - Featured Reps {% endblock%}

{% block content %}
<main role="main" class="featured-reps">
  <!-- List block -->
  <div class="row">
    <div class="large-12 columns">
      <h3>
        Featured Reps
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <p>
        This is an archive of all past "Reps of the Month". This
        special recognition is given each month by the Mozilla Reps
        Council to a Rep who has gone above and beyond to help push the
        Mozilla project forward in his/her region.
      </p>
    </div>
  </div>
  <!-- Adding new rep -->
  {% if perms.featuredrep.can_edit_featured %}
    <div class="row">
      <div class="large-12 columns align-right">
        <a href="{{ url('featuredrep_add_featured') }}"
           role="button"
           class="featured-button small button">Add new</a>
      </div>
    </div>
  {% endif %}
  <div class="row">
    <div class="large-12 columns">
      <table class="dashboard-table responsive">
        <thead>
          <tr>
            <th>
              Rep Name
            </th>
            <th>
              Featured text
            </th>
            <th>
              Date featured
            </th>
            {% if perms.profiles.can_edit_profiles %}
              <th>
                Actions
              </th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for feature in objects %}
          <tr>
            <td>
              {% for user in feature.users.all() %}
                <a href="{{ url('profiles_view_profile', user.userprofile.display_name) }}">
                  {{ user.get_full_name() }}
                </a>
              {% endfor %}
            </td>
            <td>
              <div class="markdown">
                {{ feature.text|markdown }}
              </div>
            </td>
            <td>
              {{ feature.created_on.strftime('%d-%m-%Y') }}
            </td>
            {% if (perms.featuredrep.can_edit_featured or
                   perms.featuredrep.can_delete_featured) %}
              <td>
                {% if perms.featuredrep.can_edit_featured %}
                  <a href="{{ url('featuredrep_edit_featured', feature.id) }}"
                     class="featured-edit pictogram-button">
                    <span class="pict-icon large pencil"</span>
                   </a>
                {% endif %}
                {% if perms.featuredrep.can_delete_featured %}
                  <form id="deleteform-{{ feature.id }}" method="post"
                        action="{{ url('featuredrep_delete_featured', feature.id) }}">
                    {% csrf_token %}
                    <a href="#" class="featured-delete pictogram-button">
                       <span class="pict-icon large close"</span>
                    </a>
                  </form>
                {% endif %}
              </td>
            {% endif %}
          </tr>
          {% else %}
          <tr>
            <td>
              No entries yet!
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <!-- Paginator -->
  {% include "includes/pagination.jinja" %}
</main>
{% endblock %}

{% block bottomextra %}
<script src="{{ static('featuredrep/js/featuredrep.js') }}" type="text/javascript"></script>
{% endblock %}