remo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve as serve_view

from remo.base import views as base_views
from remo.profiles import views as profiles_views


# Monkeypatch log_settings
import log_settings  # noqa

handler404 = base_views.custom_404
handler500 = base_views.custom_500
robots_txt = base_views.robots_txt

urlpatterns = [
    # 'me' urls
    url(r'^me/$', profiles_views.view_my_profile, name='profiles_view_my_profile'),
    # Profiles
    url(r'^u/', include('remo.profiles.user_urls')),
    url(r'^people/', include('remo.profiles.people_urls')),
    # Events
    url(r'^e/', include('remo.events.e_urls')),
    url(r'^events/', include('remo.events.event_urls')),
    # Reports
    url(r'^reports/', include('remo.reports.report_urls')),
    # Featuredrep
    url(r'^featured/', include('remo.featuredrep.urls')),
    # Login
    url(r'oidc/', include('mozilla_django_oidc.urls')),
    # API
    url(r'^api/', include('remo.api.urls')),
    url(r'^', include('remo.base.urls')),
    # Dashboard
    url(r'^dashboard/', include('remo.dashboard.urls')),
    # Action Items
    url(r'^actions/', include('remo.dashboard.action_urls')),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Voting
    url(r'^voting/', include('remo.voting.voting_urls')),
    url(r'^v/', include('remo.voting.v_urls')),
    # Portal base content
    url(r'^content/', include('remo.base.content_urls')),
    # Portal settings
    url(r'^settings/', include('remo.base.settings_urls')),
    # Generate a robots.txt
    url(r'^robots\.txt$', robots_txt),
    # contribute.json url
    url(r'^(?P<path>contribute\.json)$', serve_view, {'document_root': settings.ROOT}),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^404/$', handler404, name='404'),
        url(r'^500/$', handler500, name='500')
    ]
    urlpatterns += staticfiles_urlpatterns()

remo/voting/models.py
from datetime import timedelta

from django.core.urlresolvers import reverse
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.contrib.auth.models import Group, User
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.db import models, transaction
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import now

from django_statsd.clients import statsd
from uuslug import uuslug

from remo.base.tasks import send_remo_mail
from remo.celery import app as celery_app
from remo.dashboard.models import ActionItem, Item
from remo.remozilla.models import Bug
from remo.remozilla.utils import get_bugzilla_url
from remo.voting.tasks import send_voting_mail


# Voting period in days
BUDGET_REQUEST_PERIOD_START = 3
BUDGET_REQUEST_PERIOD_END = 6
VOTE_ACTION = 'Cast your vote for'
BUDGET_VOTE_ACTION = 'Cast your vote for budget request'


@python_2_unicode_compatible
class Poll(models.Model):
    """Poll Model."""
    name = models.CharField(max_length=300)
    slug = models.SlugField(blank=True, max_length=255)
    start = models.DateTimeField()
    end = models.DateTimeField()
    valid_groups = models.ForeignKey(Group, related_name='valid_polls')
    created_on = models.DateTimeField(auto_now_add=True)
    description = models.TextField(validators=[MinLengthValidator(20)])
    created_by = models.ForeignKey(User, related_name='range_polls_created')
    users_voted = models.ManyToManyField(User, related_name='polls_voted', through='Vote')
    task_start_id = models.CharField(max_length=256, blank=True,
                                     null=True, editable=False, default='')
    task_end_id = models.CharField(max_length=256, blank=True, null=True,
                                   editable=False, default='')
    bug = models.ForeignKey(Bug, null=True, blank=True)
    automated_poll = models.BooleanField(default=False)
    comments_allowed = models.BooleanField(default=True)
    is_extended = models.BooleanField(default=False)
    action_items = generic.GenericRelation(ActionItem)

    def get_absolute_url(self):
        return reverse('remo.voting.views.view_voting', args=[self.slug])

    @property
    def is_future_voting(self):
        if self.start > now():
            return True
        return False

    @property
    def is_current_voting(self):
        if self.start < now() and self.end > now():
            return True
        return False

    @property
    def is_past_voting(self):
        if self.end < now():
            return True
        return False

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_on']

    def save(self, *args, **kwargs):
        """Custom save method."""

        create_action_items = False

        if not self.pk:
            self.slug = uuslug(self.name, instance=self)
            create_action_items = True
        else:
            # Update action items
            current_poll = Poll.objects.get(id=self.pk)
            action_model = ContentType.objects.get_for_model(self)
            action_items = ActionItem.objects.filter(content_type=action_model, object_id=self.pk)

            if current_poll.end != self.end:
                action_items.update(due_date=self.end.date())

            if current_poll.valid_groups != self.valid_groups:
                action_items.delete()
                create_action_items = True

            if not settings.CELERY_TASK_ALWAYS_EAGER:
                if self.is_current_voting:
                    celery_app.control.revoke(self.task_end_id)
                elif self.is_future_voting:
                    celery_app.control.revoke(self.task_start_id)
                    celery_app.control.revoke(self.task_end_id)

            if not self.is_future_voting:
                obj = Poll.objects.get(pk=self.id)
                if self.end > obj.end:
                    self.is_extended = True

        super(Poll, self).save()

        if create_action_items:
            ActionItem.create(self)

    def get_action_items(self):
        action_items = []
        due_date = self.end.date()

        if self.automated_poll:
            name = u'{0} {1}'.format(BUDGET_VOTE_ACTION, self.bug.summary)
            priority = ActionItem.MAJOR
        else:
            name = u'{0} {1}'.format(VOTE_ACTION, self.name)
            priority = ActionItem.NORMAL

        # Exclude the users that already have voted
        users = User.objects.filter(groups=self.valid_groups).exclude(
            pk__in=self.vote_set.values_list('user', flat=True))
        for user in users:
            action_item = Item(name, user, priority, due_date)
            action_items.append(action_item)

        return action_items


@python_2_unicode_compatible
class Vote(models.Model):
    """Vote model."""
    user = models.ForeignKey(User, related_name='votes')
    poll = models.ForeignKey(Poll)
    date_voted = models.DateField(auto_now_add=True)

    def __str__(self):
        return u'{0} {1}'.format(self.user, self.poll)

    def save(self, *args, **kwargs):
        if self.poll.automated_poll:
            name = u'{0} {1}'.format(BUDGET_VOTE_ACTION, self.poll.bug.summary)
        else:
            name = u'{0} {1}'.format(VOTE_ACTION, self.poll.name)

        super(Vote, self).save(*args, **kwargs)
        ActionItem.resolve(instance=self.poll, user=self.user, name=name)


@python_2_unicode_compatible
class RangePoll(models.Model):
    """Range Poll Model."""
    name = models.CharField(max_length=500, default='')
    poll = models.ForeignKey(Poll, related_name='range_polls')

    def __str__(self):
        return self.name


class RangePollChoice(models.Model):
    """Range Poll Choice Model."""
    votes = models.IntegerField(default=0)
    range_poll = models.ForeignKey(RangePoll, related_name='choices')
    nominee = models.ForeignKey(User, limit_choices_to={'groups__name': 'Rep'})

    class Meta:
        ordering = ['nominee__first_name', 'nominee__last_name']


@python_2_unicode_compatible
class RadioPoll(models.Model):
    """Radio Poll Model."""
    question = models.CharField(max_length=500)
    poll = models.ForeignKey(Poll, related_name='radio_polls')

    def __str__(self):
        return self.question


@python_2_unicode_compatible
class RadioPollChoice(models.Model):
    """Radio Poll Choice Model."""
    answer = models.CharField(max_length=500)
    votes = models.IntegerField(default=0)
    radio_poll = models.ForeignKey(RadioPoll, related_name='answers')

    def __str__(self):
        return self.answer

    class Meta:
        ordering = ['radio_poll__question']


class PollComment(models.Model):
    """Comments in Poll."""
    user = models.ForeignKey(User)
    poll = models.ForeignKey(Poll, related_name='comments')
    created_on = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()

    def get_absolute_delete_url(self):
        return reverse('remo.voting.views.delete_poll_comment',
                       args=[self.poll.slug,
                             self.user.userprofile.display_name,
                             self.id])

    class Meta:
        ordering = ['created_on']


@receiver(post_save, sender=Poll, dispatch_uid='voting_poll_email_reminder_signal')
def poll_email_reminder(sender, instance, raw, **kwargs):
    """Send email reminders when a vote starts/ends."""
    subject_start = '[Voting] Cast your vote for "%s" now!' % instance.name
    subject_end = '[Voting] Results for "%s"' % instance.name

    start_template = 'emails/voting_starting_reminder.jinja'
    end_template = 'emails/voting_results_reminder.jinja'

    if not instance.task_start_id or instance.is_future_voting:
        start_reminder = send_voting_mail.apply_async(
            eta=instance.start, kwargs={'voting_id': instance.id,
                                        'subject': subject_start,
                                        'email_template': start_template})
        Poll.objects.filter(pk=instance.pk).update(task_start_id=start_reminder.task_id)
    if not instance.is_past_voting:
        end_reminder = send_voting_mail.apply_async(
            eta=instance.end, kwargs={'voting_id': instance.id,
                                      'subject': subject_end,
                                      'email_template': end_template})
        Poll.objects.filter(pk=instance.pk).update(task_end_id=end_reminder.task_id)


@receiver(post_save, sender=Poll, dispatch_uid='voting_automated_poll_discussion_email')
def automated_poll_discussion_email(sender, instance, created, raw, **kwargs):
    """Send email reminders when a vote starts/ends."""
    if instance.automated_poll and created:
        template = 'emails/review_budget_notify_review_team.jinja'
        subject = u'Discuss [Bug {id}] - {summary}'.format(id=instance.bug.bug_id,
                                                           summary=unicode(instance.bug.summary))
        data = {'bug': instance.bug,
                'BUGZILLA_URL': get_bugzilla_url(instance.bug),
                'poll': instance}
        send_remo_mail.delay(
            subject=subject, email_template=template,
            recipients_list=[settings.REPS_REVIEW_ALIAS],
            data=data)


@receiver(pre_delete, sender=Poll,
          dispatch_uid='voting_poll_delete_reminder_signal')
def poll_delete_reminder(sender, instance, **kwargs):
    """Revoke the task if a voting is deleted."""
    if not settings.CELERY_TASK_ALWAYS_EAGER:
        if instance.task_start_id:
            celery_app.control.revoke(instance.task_start_id)
        if instance.task_end_id:
            celery_app.control.revoke(instance.task_end_id)


@receiver(post_save, sender=Bug, dispatch_uid='remozilla_automated_poll_signal')

remo/voting/templates/vote_voting.jinja
{% extends "base_fd4.jinja" %}

{% block pagetitle %}
Mozilla Reps - {{ poll.name }} - Vote
{% endblock %}

{% block content %}
<main role="main" class="voting-main">
  <form method="post">
    {% csrf_token %}
    <div class="row">
      {% if range_poll_choice_forms|formset_errors_exist or
            radio_poll_choice_forms|formset_errors_exist %}
        <div class="large-12 columns">
          <small class="error">Please correct the errors below.</small>
        </div>
      {% endif %}
      <div class="large-8 columns">
        <h1>{{ poll.name|urlize(50) }}</h1>
      </div>
      <div class="large-4 columns align-right hide-for-small">
        {% if user_has_poll_permissions(user, poll) %}
          <a href="{{ url('voting_edit_voting', slug=poll.slug) }}"
             class="small button">
            Edit voting
          </a>
        {% endif %}
      </div>
    </div>

    <div class="row">
      <div class="large-6 columns">
        <div class="row">
          <div class="large-1 columns">
            <div class="pict-icon large time"></div>
          </div>
          <div class="large-9 pull-2 columns">
            <div class="row">
              <div class="large-12 columns end">
                <div class="voting-single-date">
                  <div class="row">
                    {% if not is_multiday(poll.start, poll.end) %}
                    {# this is single voting #}
                    <div class="large-3 small-3 columns">
                      <div class="number">
                        {{ poll.start|strftime('%d') }}
                      </div>
                    </div>
                    <div class="large-5 small-5 columns">
                      <div class="month">
                        {{ poll.start|strftime('%b %Y')|upper }}
                      </div>
                      <div class="single-day">
                        {{ poll.start|strftime('%A') }}
                      </div>
                    </div>
                    <div class="large-4 small-4 columns end">
                      <div class="date-times tip-bottom datetime-tip"
                           data-tooltip
                           data-options="disable-for-touch:true"
                           data-width="140"
                           data-date-start="{{ poll.start|format_datetime_iso }}"
                           data-date-end="{{ poll.end|format_datetime_iso }}"
                           data-is-multidate="false">
                        <div class="time-start">
                          {{ poll.start|strftime('%H:%M') }}
                        </div>
                        <div class="time-end">
                          {{ poll.end|strftime('%H:%M') }}
                        </div>
                      </div>
                    </div>
                  {% else %}
                    {# Voting is multiday #}
                    <!-- Voting is multiday -->
                    <div class="large-12 columns">
                      <div class="large-11 small-12 columns">
                        <div class="row">
                          <div class="large-7 small-6 columns date">
                            <time>
                              {{ poll.start|strftime('%d %b %Y %H:%M')|upper }}
                            </time>
                          </div>
                          <div class="large-5 small-6 columns day">
                            {{ poll.start|strftime('%A') }}
                          </div>
                        </div>
                        <div class="row">
                          <div class="large-7 small-6 columns date">
                            <time>
                              {{ poll.end|strftime('%d %b %Y %H:%M')|upper }}
                            </time>
                          </div>
                          <div class="large-5 small-6 columns day">
                            {{ poll.end|strftime('%A') }}
                          </div>
                        </div>
                      </div>
                      <div class="large-1 hide-for-small columns">
                        <div class="tip-bottom datetime-tip"
                             data-tooltip
                             data-options="disable-for-touch:true"
                             data-width="120"
                             data-date-start="{{ poll.start|format_datetime_iso }}"
                             data-date-end="{{ poll.end|format_datetime_iso }}"
                             data-is-multidate="true">
                        </div>
                      </div>
                    </div>
                  {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="large-1 columns">
            <div class="pict-icon large tag"></div>
          </div>
          <div class="large-11 columns">
            <!-- Description -->
            <p>
              <span class="label inline">
                Description
              </span>
              {{ poll.description|urlize(150)|markdown|nl2br }}
            </p>
          </div>
        </div>

        {% if range_poll_choice_forms %}
          <div class="row">
            <div class="large-1 columns">
              <!-- Editable Content wiki like -->
              <div class="pict-icon large news"></div>
            </div>
            <div class="large-11 columns">
              <p>
                Range voting is a voting method for elections under which voters score each
                candidate, the scores are added up, and the candidate(s) with the highest score win.
              </p>
              <p>
                For each candiate select from the drop down menu a score from 0 to the highest number.
                There is no quota, and you can freely assign different or same scores to different candidates.
              </p>
              <p>
                More info can be found in the Wikipedia article on
                 <a href="http://en.wikipedia.org/wiki/Range_voting" target="_blank">Range Voting</a>.
              </p>
            </div>
          </div>
        {% endif %}

      </div>

      <div class="large-6 columns">
        {% if range_poll_choice_forms %}
          <div class="row">
            <div class="large-1 columns">
              <div class="pict-icon large people"></div>
            </div>
            <div class="large-11 columns">
              <div class="meter-container">
                <span class="meter_text">{{ poll|get_meter_value }}%</span>
                <meter min="0" optimum="85" value="{{ poll|get_meter_value }}" max="100" high="80">
                  <div class="progressbar">
                    <span class="progressspan" data-percent="{{ poll|get_meter_value }}"></span>
                  </div>
                </meter>
              </div>
              <p>
                {% for range_poll, choice_form in range_poll_choice_forms.items() %}
                  <span class="label">
                    Range vote for {{ range_poll.name }}
                  </span>
                  {% for choice in choice_form %}
                    <div class="row poll-choice">
                      <div class="large-10 columns">
                        <label for="{{ choice.id_for_label }}">
                          {% set nominee=get_nominee(choice.label) %}
                          {% if nominee %}
                            <a href="{{ url('profiles_view_profile',
                               display_name=nominee|get_display_name) }}"
                               target="_blank">
                              {{ choice.label }}
                            </a>
                          {% else %}
                            {{ choice.label }}
                          {% endif %}
                        </label>
                      </div>
                      <div class="large-2 columns">
                        {{ choice }}
                      </div>
                    </div>
                    {{ field_errors(choice) }}
                  {% endfor %}
                {% endfor %}
              </p>
            </div>
          </div>
        {% endif %}

        {% if radio_poll_choice_forms %}
          <div class="row">
            <div class="large-1 columns">
              <div class="pict-icon large list"></div>
            </div>
            <div class="large-11 columns">
              <div class="meter-container">
                <span class="meter_text">{{ poll|get_meter_value }}%</span>
                <meter min="0" optimum="85" value="{{ poll|get_meter_value }}" max="100" high="80">
                  <div class="progressbar">
                    <span class="progressspan" data-percent="{{ poll|get_meter_value }}"></span>
                  </div>
                </meter>
              </div>
              <p>
                {% for radio_poll, choice_form in radio_poll_choice_forms.items() %}
                  <span class="label">
                    Vote for {{ radio_poll.question }}
                  </span>
                  {% if poll.is_current_voting and not user_voted %}
                    {% for choice in choice_form %}
                      {{ choice }}
                      {{ field_errors(choice) }}
                    {% endfor %}
                  {% endif %}
                {% endfor %}
              </p>
            </div>
          </div>
        {% endif %}

        <div class="row show-for-small controls-footer">
          <div class="small-12 columns">
            {% if user_has_poll_permissions(user, poll) and not read_only_access %}
              <a href="{{ url('voting_edit_voting', slug=poll.slug) }}"
                 class="small button">
                Edit voting
              </a>
            {% endif %}
            {% if poll.is_current_voting and not user_voted %}
              <button class="button small confirm">Vote</button>
            {% endif %}
          </div>
        </div>
      </div>
      <!-- Vote button -->
      <div class="large-4 columns align-right hide-for-small">
        {% if poll.is_current_voting and not user_voted and not read_only_access %}
          <button class="button small confirm">Vote</button>
        {% endif %}
      </div>
    </div>
  </form>

  <!-- Comments -->
  {% if poll.comments_allowed %}
    <div class="row">
      <div class="large-12 columns">
        <div class="row report-box">
          <div class="columns comment-icon">
            <div class="pict-icon large talk"></div>
          </div>
          <div class="columns report-item comment-item">
            {% for comment in poll.comments.all() %}
              <div class="report-comment">
                {% if perms.voting.delete_pollcomment or
                      comment.user == request.user %}
                  <form method="post" action="{{ comment.get_absolute_delete_url() }}">
                    {% csrf_token %}
                    <button type="submit" class="report-delete-comment">&#215;</button>
                  </form>
                {% endif %}
                <span class="label inline">
                  Comment {{ loop.index }} by&nbsp;
                </span>
                {% if comment.user.userprofile.display_name == 'ReMoBot' %}
                  {{ comment.user.get_full_name() }}
                {% else %}
                  <a href="{{ url('profiles_view_profile', comment.user|get_display_name) }}">
                    {{ comment.user.get_full_name() }}
                  </a>
                {% endif %}
                <span data-time="{{ comment.created_on|format_datetime_iso }}"
                      title="{{ comment.created_on }}">
                  at {{ comment.created_on }}
                </span><br>
                {% if comment.user.userprofile.display_name == 'ReMoBot' %}
                  {{ comment.comment|markdown }}
                {% else %}
                  {{ comment.comment|urlize(50) }}
                {% endif %}
              </div>
            {% endfor %}
            <div id="report-comment-post">
              <form method="post" actions="{{ poll.get_absolute_url() }}"
                    class="custom">
                {% csrf_token %}
                {{ field_with_attrs(comment_form.comment,
                                    class="flat",
                                    placeholder="Add comment to this poll") }}
                {{ field_errors(comment_form.comment) }}
                <div id="post-comment" class="align-right">
                  <button type="submit" class="small button">
                    Post comment
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

</main>
{% endblock %}

{% block bottomextra %}
  {% compress js %}
    <script src="{{ static('voting/js/voting_view_voting.js') }}"></script>
  {% endcompress %}
{% endblock %}