remo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve as serve_view

from remo.base import views as base_views
from remo.profiles import views as profiles_views


# Monkeypatch log_settings
import log_settings  # noqa

handler404 = base_views.custom_404
handler500 = base_views.custom_500
robots_txt = base_views.robots_txt

urlpatterns = [
    # 'me' urls
    url(r'^me/$', profiles_views.view_my_profile, name='profiles_view_my_profile'),
    # Profiles
    url(r'^u/', include('remo.profiles.user_urls')),
    url(r'^people/', include('remo.profiles.people_urls')),
    # Events
    url(r'^e/', include('remo.events.e_urls')),
    url(r'^events/', include('remo.events.event_urls')),
    # Reports
    url(r'^reports/', include('remo.reports.report_urls')),
    # Featuredrep
    url(r'^featured/', include('remo.featuredrep.urls')),
    # Login
    url(r'oidc/', include('mozilla_django_oidc.urls')),
    # API
    url(r'^api/', include('remo.api.urls')),
    url(r'^', include('remo.base.urls')),
    # Dashboard
    url(r'^dashboard/', include('remo.dashboard.urls')),
    # Action Items
    url(r'^actions/', include('remo.dashboard.action_urls')),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Voting
    url(r'^voting/', include('remo.voting.voting_urls')),
    url(r'^v/', include('remo.voting.v_urls')),
    # Portal base content
    url(r'^content/', include('remo.base.content_urls')),
    # Portal settings
    url(r'^settings/', include('remo.base.settings_urls')),
    # Generate a robots.txt
    url(r'^robots\.txt$', robots_txt),
    # contribute.json url
    url(r'^(?P<path>contribute\.json)$', serve_view, {'document_root': settings.ROOT}),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^404/$', handler404, name='404'),
        url(r'^500/$', handler500, name='500')
    ]
    urlpatterns += staticfiles_urlpatterns()

remo/reports/models.py
import datetime

from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import m2m_changed, post_save, pre_delete
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import now

from django_statsd.clients import statsd
from product_details import product_details

import remo.base.utils as utils
from remo.base.models import GenericActiveManager
from remo.base.tasks import send_remo_mail
from remo.base.utils import daterange, get_date, get_object_or_none
from remo.dashboard.models import ActionItem, Item
from remo.events.models import Attendance as EventAttendance, Event
from remo.profiles.models import FunctionalArea
from remo.reports import (ACTIVITY_CAMPAIGN, ACTIVITY_EVENT_ATTEND,
                          ACTIVITY_EVENT_CREATE, ACTIVITY_POST_EVENT_METRICS,
                          READONLY_ACTIVITIES, VERIFIABLE_ACTIVITIES)


COUNTRIES_LIST = product_details.get_regions('en').values()
VERIFY_ACTIVITY_WEEKS = 2
VERIFY_ACTION = 'Verify the activity of'


@python_2_unicode_compatible
class Activity(models.Model):
    name = models.CharField(max_length=100)
    active = models.BooleanField(default=True)

    objects = models.Manager()
    active_objects = GenericActiveManager()

    class Meta:
        ordering = ['name']
        verbose_name = 'activity'
        verbose_name_plural = 'activities'

    def __str__(self):
        return self.name

    def get_absolute_edit_url(self):
        return reverse('edit_activity', kwargs={'pk': self.id})

    @property
    def is_editable(self):
        """Check if activity is editable."""
        return self.name not in READONLY_ACTIVITIES

    @property
    def is_verifiable(self):
        """Check if the activity is verifiable."""
        if self.name in VERIFIABLE_ACTIVITIES:
            return True
        return False


@python_2_unicode_compatible
class Campaign(models.Model):
    """Campaign/Initiatives model.

    As of March 2015 this serves as the Initiative model used both
    in events and reports app.
    """
    name = models.CharField(max_length=100)
    active = models.BooleanField(default=True)

    objects = models.Manager()
    active_objects = GenericActiveManager()

    class Meta:
        ordering = ['name']
        verbose_name = 'initiative'
        verbose_name_plural = 'initiatives'

    def __str__(self):
        return self.name

    def get_absolute_edit_url(self):
        return reverse('edit_campaign', kwargs={'pk': self.id})


@python_2_unicode_compatible
class NGReport(models.Model):
    """ Continuous Reporting Model.

    In order to be able to distinguish the old
    and the new Report models, each model associated
    with the continuous reporting system will have the
    'NG' prefix (NG - New Generation).
    """
    user = models.ForeignKey(User, related_name='ng_reports')
    report_date = models.DateField(db_index=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    mentor = models.ForeignKey(User, null=True, on_delete=models.SET_NULL,
                               related_name='ng_reports_mentored')
    activity = models.ForeignKey(Activity, related_name='ng_reports')
    campaign = models.ForeignKey(Campaign, null=True, blank=True, related_name='ng_reports')
    functional_areas = models.ManyToManyField(FunctionalArea, related_name='ng_reports')
    longitude = models.FloatField(blank=False, null=True)
    latitude = models.FloatField(blank=False, null=True)
    location = models.CharField(max_length=150, blank=True, default='')
    is_passive = models.BooleanField(default=False)
    event = models.ForeignKey(Event, null=True, blank=True)
    link = models.URLField(max_length=500, blank=True, default='')
    link_description = models.CharField(max_length=500, blank=True, default='')
    activity_description = models.TextField(blank=True, default='')
    verified_activity = models.BooleanField('I have verified this activity',
                                            blank=True, default=False)
    country = models.CharField(max_length=50, blank=True, default='')
    action_items = generic.GenericRelation(ActionItem)

    def _get_url_args(self):
        args = [self.user.userprofile.display_name,
                self.report_date.year,
                utils.number2month(self.report_date.month),
                self.report_date.day,
                self.id]
        return args

    def get_absolute_url(self):
        return reverse('remo.reports.views.view_ng_report', args=self._get_url_args())

    def get_absolute_edit_url(self):
        return reverse('remo.reports.views.edit_ng_report', args=self._get_url_args())

    def get_absolute_delete_url(self):
        return reverse('remo.reports.views.delete_ng_report', args=self._get_url_args())

    @property
    def get_report_date(self):
        return self.report_date.strftime('%d %b %Y')

    @property
    def is_future_report(self):
        if self.report_date > now().date():
            return True
        return False

    def save(self, *args, **kwargs):
        """Override save for custom functionality."""

        # Make last report notificaton date NULL on new report
        today = get_date()
        if self.pk is None and self.user.userprofile.first_report_notification:
            start = today - datetime.timedelta(weeks=4)
            end = today + datetime.timedelta(weeks=4)
            if self.report_date in daterange(start, end):
                self.user.userprofile.first_report_notification = None
                self.user.userprofile.second_report_notification = None
                self.user.userprofile.save()

        # User streaks functionality
        one_week = datetime.timedelta(7)
        current_start = self.user.userprofile.current_streak_start or None
        longest_start = self.user.userprofile.longest_streak_start or None
        longest_end = self.user.userprofile.longest_streak_end or None

        # Save the mentor of the user if no mentor is defined.
        if not self.mentor:
            self.mentor = self.user.userprofile.mentor
        # Save the country if possible
        saved_report = get_object_or_none(NGReport, id=self.id)
        if (saved_report and (saved_report.latitude != self.latitude
                              or saved_report.longitude != self.longitude)):
            country = None
            try:
                country = self.location.split(',')[-1].strip()
            except IndexError:
                pass
            if country in COUNTRIES_LIST:
                self.country = country
        super(NGReport, self).save()

        # Resolve the verified action items.
        action_item_name = u'{0} {1}'.format(VERIFY_ACTION, self.user.get_full_name())
        if self.verified_activity:
            ActionItem.resolve(instance=self,
                               user=self.mentor,
                               name=action_item_name)
        else:
            # Create all the action items, if any
            ActionItem.create(self)

        if self.is_future_report:
            return

        # If there is already a running streak and the report date
        # is within this streak, update the current streak counter.
        if (current_start and self.report_date < current_start
                and self.report_date in daterange((current_start - one_week), current_start)):
            current_start = self.report_date
        # If there isn't any current streak, and the report date
        # is within the current week, let's start the counting.
        elif not current_start and self.report_date in daterange(get_date(-7), today):
            current_start = self.report_date

        # Longest streak section
        # If longest streak already exists, let's update it.
        if longest_start and longest_end:

            # Compare the number of reports registered during
            # the current streak and the number of reports
            # during the longest streak. If current streak is bigger
            # than the previous longest streak, update the longest streak.
            longest_streak_count = NGReport.objects.filter(
                report_date__range=(longest_start, longest_end),
                user=self.user).count()
            current_streak_count = NGReport.objects.filter(
                report_date__range=(current_start, today),
                user=self.user).count()
            if current_start and current_streak_count > longest_streak_count:
                longest_start = current_start
                longest_end = today

            # This happens only when a user appends a report, dated in the
            # range of longest streak counters and it's out of the range
            # of current streak counter.
            elif self.report_date in daterange(longest_start - one_week, longest_end + one_week):
                if self.report_date < longest_start:
                    longest_start = self.report_date
                elif self.report_date > longest_end:
                    longest_end = self.report_date
        else:
            # Longest streak counters are empty, let's setup their value
            longest_start = self.report_date
            longest_end = self.report_date
        # Assign the calculated values, to user's profile.
        self.user.userprofile.current_streak_start = current_start
        self.user.userprofile.longest_streak_start = longest_start
        self.user.userprofile.longest_streak_end = longest_end
        self.user.userprofile.save()

    def get_action_items(self):
        """Returns a list of action items.

        An action item is returned in the case that an activity needs
        verification from the mentor of a user.
        """

        action_items = []

remo/reports/api/views.py
from collections import namedtuple
from datetime import datetime, timedelta

from django.shortcuts import get_object_or_404
from django.utils.timezone import now

import django_filters
from rest_framework.views import APIView
from rest_framework.response import Response

from remo.api.views import BaseReadOnlyModelViewset
from remo.api.serializers import BaseKPISerializer
from remo.base.utils import get_quarter
from remo.reports.api.serializers import (ActivitiesDetailedSerializer,
                                          ActivitiesSerializer)
from remo.reports.models import NGReport


KPI_WEEKS = 12


class ActivitiesFilter(django_filters.FilterSet):
    user = django_filters.CharFilter(name='user__userprofile')
    activity = django_filters.CharFilter(name='activity__name')
    initiative = django_filters.CharFilter(name='campaign__name')
    mentor = django_filters.CharFilter(name='mentor__userprofile')
    category = django_filters.CharFilter(name='functional_areas__name')

    class Meta:
        model = NGReport
        fields = ('is_passive', 'event', 'activity_description', 'report_date',
                  'location', 'longitude', 'latitude', 'link',
                  'link_description')


class ActivitiesViewSet(BaseReadOnlyModelViewset):
    """Return a list of activities."""
    serializer_class = ActivitiesSerializer
    model = NGReport
    queryset = NGReport.objects.all()
    filter_class = ActivitiesFilter

    def retrieve(self, request, pk):
        report = get_object_or_404(self.get_queryset(), pk=pk)
        serializer = ActivitiesDetailedSerializer(report,
                                                  context={'request': request})
        return Response(serializer.data)

    def get_queryset(self):
        orderby = self.request.query_params.get('orderby', 'DESC')

        if orderby == 'ASC':
            self.queryset = self.queryset.order_by('report_date')
        return self.queryset


class ActivitiesKPIFilter(django_filters.FilterSet):
    """Filter for activities KPI endpoint."""
    category = django_filters.CharFilter(name='functional_areas__name')
    initiative = django_filters.CharFilter(name='campaign__name')

    class Meta:
        model = NGReport
        fields = ['country', 'category', 'initiative']


class ActivitiesKPIView(APIView):

    def get(self, request):
        """Returns serialized data for Activities KPI"""

        qs = NGReport.objects.filter(report_date__lte=now())
        activities = ActivitiesKPIFilter(request.query_params, queryset=qs)
        weeks = int(request.query_params.get('weeks', KPI_WEEKS))

        # Total number of activities to day
        total = activities.qs.count()

        # Quarter calculations
        current_quarter_start = get_quarter()[1]

        # Total number of activities for current quarter
        quarter_total = activities.qs.filter(
            report_date__gte=current_quarter_start).count()

        # Total number of activities for the previous quarter
        previous_quarter_end = current_quarter_start - timedelta(days=1)
        previous_quarter_start = get_quarter(previous_quarter_end)[1]
        previous_quarter_total = activities.qs.filter(
            report_date__range=[previous_quarter_start,
                                previous_quarter_end]).count()

        diff = quarter_total - previous_quarter_total
        try:
            # Percentage change of activities since start of quarter
            percent_quarter = diff / float(previous_quarter_total)
        except ZeroDivisionError:
            if diff > 0:
                percent_quarter = 100
            else:
                percent_quarter = 0

        # Week calculations
        today = datetime.combine(now().date(), datetime.min.time())
        current_week_start = today - timedelta(days=now().weekday())
        prev_week_start = current_week_start - timedelta(weeks=1)

        # Total number of activities this week
        week_total = activities.qs.filter(
            report_date__gte=current_week_start).count()
        query_range = [prev_week_start, current_week_start]

        # Total number of activities for previous week
        prev_week_total = activities.qs.filter(
            report_date__range=query_range).count()

        diff = week_total - prev_week_total
        try:
            # Percentage change of activities compared with previous week
            percent_week = diff / float(prev_week_total)
        except ZeroDivisionError:
            if diff > 0:
                percent_week = 100
            else:
                percent_week = 0

        weekly_count = []
        for i in range(weeks):
            start = current_week_start - timedelta(weeks=i)
            end = start + timedelta(weeks=1)

            # Total number of activities (per week) for previous weeks
            count = activities.qs.filter(
                report_date__range=[start, end]).count()
            weekly_count.append({'week': weeks - i, 'activities': count})

        kwargs = {
            'total': total,
            'quarter_total': quarter_total,
            'quarter_growth_percentage': percent_quarter * 100,
            'week_total': week_total,
            'week_growth_percentage': percent_week * 100,
            'total_per_week': weekly_count
        }

        kpi = namedtuple('ActivitiesKPI', kwargs.keys())(*kwargs.values())
        serializer = BaseKPISerializer(kpi)

        return Response(serializer.data)

remo/reports/templates/edit_ng_report.jinja
{% extends "base_fd4.jinja" %}

{% block pagetitle %}
  {{ super() }} - {% if created %}Add{% else %}Edit{% endif %} report
{% endblock %}

{% block content %}
<main role="main" class="reports-main">
  <form id="active-report-form" method="post">
    {% csrf_token %}

    <div class="row">
      {% if report_form.errors %}
        <div class="large-12 columns">
          <small class="error">Please correct the errors below.</small>
        </div>
      {% endif %}
      <div class="large-6 columns">
        <h1>
          {% if created %}Add{% else %}Edit{% endif %} report
        </h1>
      </div>
      <div class="large-6 columns align-right hide-for-small">
        {% if not created %}
          <button type="button" class="small button alert"
                  data-reveal-id="ng-delete-report">Delete report</button>
        {% endif %}
        <button type="submit" class="small button confirm">Save report</button>
      </div>
    </div>

    <div class="row">
      <div class="large-6 columns">
        <div class="row">
          <div class="large-1 columns">
            <div class="pict-icon large tag"></div>
          </div>
          <div class="large-11 columns">
            <label class="required" for="activity-type">
              What did you do?
            </label>
            <div id="activity-type" class="activity-type">
              {{ report_form.activity }}
            </div>
            {{ field_errors(report_form.activity) }}
          </div>
        </div>

        <div class="row">
          <div class="large-1 columns">
            <div class="pict-icon large medal"></div>
          </div>

          <div class="large-11 columns">
            <label class="required" for="campaign">
              Which initiative did you participate in?
            </label>
            <div id="campaign"
                 required>
              {{ report_form.campaign  }}
            </div>
            {{ field_errors(report_form.campaign) }}
          </div>
        </div>

        <div class="row">
          <div class="large-1 columns">
            <div class="pict-icon large time"></div>
          </div>
          <div class="large-11 columns">
            <label class="required" for="id_report_date">
              When did you do this activity?
            </label>
            <span placeholder="DD-MM-YYYY"
                  required>
              {{ field_with_attrs(report_form.report_date,
                                  class="datepicker",
                                  autocomplete="off",
                                  readonly="readonly") }}
            </span>
          </div>
        </div>
        {{ field_errors(report_form.report_date) }}
        <div class="row">
          <div class="large-1 columns">
            <div class="pict-icon large heart"></div>
          </div>
          <div class="large-11 columns">
            <label class="required" for="id_functional_areas">
              Which contribution area does your activity support?
            </label>
            {{ field_with_attrs(report_form.functional_areas,
                                class='contribution-area') }}
          </div>
        </div>
          {{ field_errors(report_form.functional_areas) }}
      </div>
      <div class="large-6 columns">

        <div class="row">
          <div class="large-1 columns">
            <div class="pict-icon large pin"></div>
          </div>
          <div class="large-11 columns">

            <label class="required" for="id_location">
              Where did your contribution take place?
            </label>
            <div class="location-inputs">
              {{ field_with_attrs(report_form.location,
                                  readonly="readonly",
                                  placeholder="City, Area, Country or Region") }}
              <button type="button"
                      class="small button pict-button locate"
                      data-reveal-id="map-point">Choose a location
              </button>
              {{ report_form.longitude }}
              {{ report_form.latitude }}
            </div>
            {# Avoid displaying two separate errors for lat and lon. #}
            {% if report_form.latitude.errors or report_form.longitude.errors %}
              <small class="error">
                Please point venue in map.
              </small>
            {% endif %}
          </div>
        </div>

        <div class="row">
          <div class="large-1 columns">
            <div class="pict-icon large www"></div>
          </div>
          <div class="large-11 columns">
            <label for="link">
              URL for your activity
            </label>
            <div id="link">
              {{ field_with_attrs(report_form.link,
                                  placeholder="http://www.example.com") }}
            </div>
            {{ field_errors(report_form.link) }}
          </div>
        </div>

        <div class="row">
          <div class="large-1 columns">
            <div class="pict-icon large edit"></div>
          </div>
          <div class="large-11 columns">
            <label for="link-description">
              URL description
            </label>
            <div id="link-description ">
              {{ field_with_attrs(report_form.link_description,
                                  class="flat",
                                  placeholder="What is this URL for") }}
            </div>
            {{ field_errors(report_form.link_description) }}
          </div>
        </div>

        <div class="row">
          <div class="large-1 columns">
            <div class="pict-icon large edit"></div>
          </div>
          <div class="large-11 columns">
            <label for="description">
              Activity description
            </label>
            <div id="description">
              {{ field_with_attrs(report_form.activity_description,
                                  class="flat",
                                  placeholder="Describe the activity briefly",
                                  rows=3) }}
            </div>
            {{ field_errors(report_form.activity_description) }}
          </div>
        </div>
      </div>
    </div>

    <div class="row show-for-small">
      <div class="large-12 columns">
        {% if not created %}
          <button type="button" class="small button alert"
                  data-reveal-id="ng-delete-report">Delete report</button>
        {% endif %}
        <button type="submit" class="small button confirm">Save report</button>
      </div>
    </div>

    <!-- Map Point Reveal Modal -->
    {% include 'includes/map_modal.jinja' %}

  </form>

  <!-- Delete Profile Reveal Modal -->
  {% if not created %}
    <div id="ng-delete-report" class="reveal-modal small">
      <a class="close-reveal-modal">&#215;</a>
      <p class="lead">Are you sure you want to do that?</p>
      <h2>Warning!</h2>
      <p>
        By pressing the following button, you will permanently and irreversibly delete this
        report.
      </p>
        <form method="post"
              action="{{ report.get_absolute_delete_url() }}">
          {% csrf_token %}
          <button class="large button alert">Delete report</button>
        </form>
    </div>
  {% endif %}
</main>

{% endblock %}

{% block bottomextra %}
  {% compress css %}
    <link rel="stylesheet" href="{{ static('events/css/jquery-ui-1.10.0.custom.css') }}"
          media="screen,projection,tv" />
    <link rel="stylesheet" href="{{ static('base/css/mapbox.css') }}"
          media="screen,projection,tv" />
    <link rel="stylesheet" href="{{ static('base/css/L.Control.Locate.css') }}"
          media="screen,projection,tv">
  {% endcompress %}
  {% compress js %}
    <script src="{{ static('base/js/mapbox.js') }}"></script>
    <script src="{{ static('base/js/L.Control.Locate.js') }}"></script>
    <script src="{{ static('events/js/jquery-ui-1.10.0.custom.js') }}"></script>
    <script src="{{ static('base/js/map_modal.js') }}"></script>
    <script src="{{ static('reports/js/edit_ng_report.js') }}"></script>
  {% endcompress %}
{% endblock %}